// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "nav": {
    "brand": "Pagix",
    "signIn": "Sign In",
    "getStarted": "Get Started"
  },
  "hero": {
    "badge": "AI-Powered Website Builder",
    "title": "Build Websites Without Code",
    "subtitle": "Create stunning, responsive websites with our drag-and-drop editor. No coding required. Launch in minutes.",
    "cta": {
      "primary": "Start Building Free",
      "secondary": "Watch Demo"
    }
  },
  "features": {
    "title": "Powerful Features",
    "subtitle": "Everything you need to create professional websites",
    "items": [
      {
        "title": "Drag & Drop Editor",
        "description": "Intuitive interface for building pages without touching code"
      },
      {
        "title": "Design System",
        "description": "Pre-built components and templates to get started instantly"
      },
      {
        "title": "Code Export",
        "description": "Export clean, production-ready HTML, CSS, and JavaScript"
      },
      {
        "title": "AI Generation",
        "description": "Let AI help generate content and design suggestions"
      },
      {
        "title": "Collaboration",
        "description": "Work with your team in real-time on projects"
      },
      {
        "title": "Responsive Design",
        "description": "Automatically optimized for all devices and screen sizes"
      }
    ]
  },
  "cta": {
    "title": "Ready to Build?",
    "subtitle": "Join thousands of creators building amazing websites with Pagix",
    "button": "Get Started Free"
  },
  "footer": {
    "brand": "Pagix",
    "copyright": "© 2025 Pagix. All rights reserved."
  },
  "dashboard": {
    "welcome": {
      "title": "Welcome back!",
      "subtitle": "Create a new page or continue editing your existing projects"
    },
    "quickActions": {
      "createBlank": "Create Blank Page",
      "chooseTemplate": "Choose Template"
    },
    "myPages": {
      "title": "My Pages",
      "searchPlaceholder": "Search pages...",
      "statuses": {
        "published": "Published",
        "draft": "Draft"
      }
    },
    "templates": {
      "title": "Start from Template",
      "subtitle": "Choose from our collection of professionally designed templates"
    }
  },
 "templates": {
    "portfolio": "Portfolio",
    "ecommerce": "E-Commerce",
    "blog": "Blog",
    "saas": "SaaS",
    "agency": "Agency",
    "restaurant": "Restaurant",
    "useTemplate": "Use Template"
  },
   "sidebar": {
    "logo": "Pagix",
    "dashboard": "Dashboard",
    "createPage": "Create Page",
    "settings": "Settings",
    "logout": "Logout"
 },
 "signup": {
    "backHome": "Back to home",
    "logo": "Pagix",
    "title": "Create Account",
    "subtitle": "Start building amazing websites today",
    "fullName": "Full Name",
       "email": " Email",
    "phone": " Phone",
    "password": " Password",
    "confirmPassword": "Confirm your Password",
    "fullNamePlaceholder": "John Doe",
    "emailPlaceholder": "you@example.com",
    "phonePlaceholder": "Enter your phone",
    "passwordPlaceholder": "Enter your password",
    "confirmPasswordPlaceholder": "Confirm your password",
    "createAccount": "Create Account",
    "creatingAccount": "Creating Account...",
    "benefitsTitle": "What you get:",
    "benefit1": "Unlimited projects",
    "benefit2": "AI-powered design",
    "benefit3": "Code export",
    "alreadyHaveAccount": "Already have an account?",
    "signIn": "Sign in",
    "emailConfirm": "Please check your email to confirm your account.",
    "error": "An unexpected error occurred. Please try again."
  },
   "login": {
    "back": "Back to home",
    "title": "Welcome Back",
    "subtitle": "Sign in to your account to continue building",
    "email": " Email",
     "password": " Password",
    "remember": "Remember me",
    "forgot": "Forgot password?",
    "signin": "Sign In",
    "signinLoading": "Signing in...",
        "passwordPlaceholder": "Enter your password",
    "divider": "Or continue with",
    "google": "Continue with Google",
    "googleLoading": "Connecting...",
    "noAccount": "Don't have an account?",
    "signup": "Sign up",
    "invalid": "Invalid email or password. Please try again.",
    "success": "Login successful. Redirecting...",
    "error": "Something went wrong. Try later!"
  },
   "forgotPassword": {
    "title": "Forgot Password?",
    "description": "No worries, we'll send you reset instructions.",
    "emailLabel": "Email address",
    "emailPlaceholder": "Enter your email",
    "phoneLabel": "Phone number",
    "phonePlaceholder": "Enter your phone",
    "sendButton": "Send reset link",
    "sendSMSButton": "Send verification code",
    "sending": "Sending...",
    "errorRequired": "Email is required",
    "errorInvalid": "Please enter a valid email address",
    "phoneErrorRequired": "Phone number is required",
    "phoneErrorInvalid": "Please enter a valid phone number",
    "successTitle": "Check your inbox",
    "successDescription": "We sent a password reset link to",
    "successInstructions": "Please check your inbox and click the link to reset your password.",
    "phoneSuccessDescription": "We sent a verification code to",
    "phoneSuccessInstructions": "Please check your messages and enter the code to reset your password.",
    "noEmail": "Didn't receive the email? Check your spam folder or try again.",
    "noSMS": "Didn't receive the SMS? Please wait a moment or try again.",
    "tryAnother": "Try another email/phone",
    "backToLogin": "Back to Login",
    "rememberPassword": "Remember your password?",
    "signIn": "Sign in",
    "emailMethod": "Email",
    "phoneMethod": "Phone",
      "back": "Back",
    "otpTitle": "Enter Verification Code",
    "otpDescription": "We sent a 6-digit code to",
    "verifying": "Verifying...",
    "verifyButton": "Verify Code",
    "didntReceiveCode": "Didn't receive the code?",
    "resendCode": "Resend Code",
        "sendSmsButton": "Send SMS"
     

   
  },
   "resetPassword": {
    "backToLogin": "Back to login",
    "title": "Set new password",
    "description": "Enter a new password for your account. Make sure it's strong and unique.",
    "newPasswordLabel": "New password",
    "newPasswordPlaceholder": " new password",
    "confirmPasswordLabel": "Confirm password",
    "confirmPasswordPlaceholder": "Confirm your new password",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "resetButton": "Reset password",
    "resetting": "Resetting...",
    "requirementsTitle": "Password requirements:",
    "requirement1": "• At least 8 characters long",
    "requirement2": "• Contains uppercase letter (A-Z)",
    "requirement3": "• Contains lowercase letter (a-z)",
    "requirement4": "• Contains number (0-9)",
    "errorAllFields": "Please fill in all fields",
    "errorTooShort": "Password must be at least 8 characters long",
    "errorNoUppercase": "Password must contain at least one uppercase letter",
    "errorNoLowercase": "Password must contain at least one lowercase letter",
    "errorNoNumber": "Password must contain at least one number",
    "errorNoMatch": "Passwords do not match",
    "successTitle": "Password reset successful",
    "successDescription": "Your password has been reset successfully. You can now sign in with your new password.",
    "goToDashboard": "Go to Dashboard"
  },
   "verifyPhone": {
    "backToSignup": "Back to signup",
    "title": "Verify Your Phone",
    "description": "Enter the 6-digit code sent to",
    "codeLabel": "Verification Code",
    "codePlaceholder": "123456",
    "verifyButton": "Verify Phone",
    "verifying": "Verifying...",
    "resendButton": "Resend Code",
    "resending": "Resending...",
    "resendIn": "Resend in {seconds}s",
    "successTitle": "Phone verified successfully!",
    "successMessage": "Welcome to Pagix!",
    "errorVerification": "Verification failed",
    "errorResend": "Failed to resend code",
    "errorGeneric": "Something went wrong!",
    "smsError": "Failed to send SMS. Please try resending."
  }
};
export default messages;